[project]
name = "HW2"
version="0.1"

dependencies=["autopep8-2.3.1","pycodestyle-2.12.1","pylint","pyflakes-3.2.0"]

[tool.autopep8]
max_line_length = 50
in-place = true
recursive = true
aggressive = 1
