name: Bandit Testing

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - name: Install all dependencies
      run: pip install .
    - name: Running Bandit for merge sort
      run: bandit src/hw2_debugging.py
