name: Merge sort

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - name: Install all dependencies
      run: pip install .
    - name: Test with pytest
      run: pytest
    - name: Autopep8
      run: autopep8 src/
    - name: Running pylint for merge sort
      run: pylint src/hw2_debugging.py
    - name: Running pylint for random numbers
      run: pylint src/rand.py
    - name: Running bandit for merge sort
      run: bandit src/hw2_debugging.py
    - name: Running bandit for random numbers
      run: bandit src/rand.py
